"""UI-facing core client facade."""

from warhammer40k_arcade_ui.core_client.fake_client import (
    FakeCoreClient,
    SubmittedFiniteDecision,
    SubmittedMovementPayload,
    SubmittedParameterizedPayload,
)
from warhammer40k_arcade_ui.core_client.local_session_client import LocalSessionClient
from warhammer40k_arcade_ui.core_client.protocol import (
    JsonObject,
    JsonValue,
    UiBattlefieldProjection,
    UiCapabilityManifest,
    UiClientProtocolError,
    UiClientStatus,
    UiClientSubmissionError,
    UiCoreClient,
    UiDecision,
    UiEventDelta,
    UiFiniteOption,
    UiGameView,
    UiInteractionConstraints,
    UiInteractionDescriptor,
    UiInteractionDisplayHints,
    UiInteractionSubmissionVariant,
    UiInvalidDiagnostic,
    UiLifecycleStatusEnvelope,
    UiMovementProposalRequest,
    UiNetworkEventDelta,
    UiParameterizedProposalRequest,
    UiPlacementProposalRequest,
    UiRulesCatalogReference,
    UiRulesCatalogView,
    UiSupportProfile,
)

__all__ = [
    "FakeCoreClient",
    "JsonObject",
    "JsonValue",
    "LocalSessionClient",
    "SubmittedFiniteDecision",
    "SubmittedMovementPayload",
    "SubmittedParameterizedPayload",
    "UiBattlefieldProjection",
    "UiCapabilityManifest",
    "UiClientProtocolError",
    "UiClientStatus",
    "UiClientSubmissionError",
    "UiCoreClient",
    "UiDecision",
    "UiEventDelta",
    "UiFiniteOption",
    "UiGameView",
    "UiInteractionConstraints",
    "UiInteractionDescriptor",
    "UiInteractionDisplayHints",
    "UiInteractionSubmissionVariant",
    "UiInvalidDiagnostic",
    "UiLifecycleStatusEnvelope",
    "UiMovementProposalRequest",
    "UiNetworkEventDelta",
    "UiParameterizedProposalRequest",
    "UiPlacementProposalRequest",
    "UiRulesCatalogReference",
    "UiRulesCatalogView",
    "UiSupportProfile",
]
