"""Local-only UI state."""

from warhammer40k_arcade_ui.state.entity_selection import (
    EntityAliasRule,
    EntityLayerDefinition,
    EntityRef,
    EntitySelectionDiagnostic,
    EntitySelectionError,
    EntitySelectionProfile,
    EntitySelectionState,
    SelectionCardinality,
    build_entity_selection_profile,
    entity_layer_registry,
    entity_ref_for_model,
    entity_ref_for_unit,
    finite_unit_entity_selection_profile,
    inspection_entity_selection_profile,
    model_entity_ref,
    movement_entity_selection_profile,
    unit_entity_ref,
    unsupported_entity_selection_profile,
    visual_anchor_diagnostics,
)
from warhammer40k_arcade_ui.state.finite_decision import (
    FiniteDecisionSubmission,
    FiniteDecisionUiState,
    submit_finite_option,
)
from warhammer40k_arcade_ui.state.movement_draft import (
    MovementAssignmentView,
    MovementDraft,
    MovementDraftError,
    MovementModelPath,
    movement_proposal_for_selected_unit,
    unsupported_parameterized_tool_label,
)
from warhammer40k_arcade_ui.state.selection import (
    ModelHit,
    SelectionState,
    model_hits_at,
    selected_model,
    selected_unit,
    unit_center,
)

__all__ = [
    "EntityAliasRule",
    "EntityLayerDefinition",
    "EntityRef",
    "EntitySelectionDiagnostic",
    "EntitySelectionError",
    "EntitySelectionProfile",
    "EntitySelectionState",
    "FiniteDecisionSubmission",
    "FiniteDecisionUiState",
    "ModelHit",
    "MovementAssignmentView",
    "MovementDraft",
    "MovementDraftError",
    "MovementModelPath",
    "SelectionCardinality",
    "SelectionState",
    "build_entity_selection_profile",
    "entity_layer_registry",
    "entity_ref_for_model",
    "entity_ref_for_unit",
    "finite_unit_entity_selection_profile",
    "inspection_entity_selection_profile",
    "model_entity_ref",
    "model_hits_at",
    "movement_entity_selection_profile",
    "movement_proposal_for_selected_unit",
    "selected_model",
    "selected_unit",
    "submit_finite_option",
    "unit_center",
    "unit_entity_ref",
    "unsupported_entity_selection_profile",
    "unsupported_parameterized_tool_label",
    "visual_anchor_diagnostics",
]
